language: python
install:
  - pip install -r tests/requirements.txt
python:
  - 2.7
  - 3.3
  - 3.4
script:
  - nosetests --with-coverage
after_success:
  - coveralls

notifications:
  email:
    recipients:
      - chris+travis@chrisdown.name
    on_success: never
    on_failure: always
